### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by nscavell** [vert-x3/vertx-mongo-client#1]
Currently SSL is configurable, but not supported as it uses a different StreamFactory (Netty). We could have version conflicts with the Netty that mongo uses and the one vertx uses.

**Comment by johnoliver** [comment]
Although better support should be added, at the moment I am using SSL without issues. The quick work around is to set the `org.mongodb.async.type` property before creating any clients, with:
```
System.setProperty("org.mongodb.async.type", "netty");
```

**Comment by cescoffier** [comment]
Postponed to 3.3.0

**Comment by MazizEsa** [comment]
Will give a try on this one as well.

**Comment by MazizEsa** [comment]
@cescoffier @karianna any suggestion on the best way to run test with the ssl enabled? It seems embed.mongo will always download mongo without ssl enabled both on linux and mac os.

**Comment by MazizEsa** [comment]
@cescoffier @karianna any suggestion on the best way to run test with the ssl enabled? It seems embed.mongo will always download mongo without ssl enabled both on linux and mac os.

**Comment by karianna** [comment]
@johnoliver got around this for us locally (I think he had to build his own
SSL'd mongo) - John?

Cheers,
Martijn

**Comment by MazizEsa** [comment]
@johnoliver you inputs would be much appreciated.

**Comment by MazizEsa** [comment]
Sorry got my hands full currently. Will try to allocate time for this.

**Comment by munsuri** [comment]
I hit the same issue with **vertx-mongo-client:3.4.1** while trying to use [MongoDB Atlas](https://www.mongodb.com/cloud/atlas).

`java.lang.UnsupportedOperationException: No SSL support in java.nio.channels.AsynchronousSocketChannel. For SSL support use com.mongodb.connection.netty.NettyStreamFactoryFactory
2017-05-05T22:44:26.040505+00:00 app[web.1]: 	at com.mongodb.connection.AsynchronousSocketChannelStreamFactory.<init>(AsynchronousSocketChannelStreamFactory.java:41)
2017-05-05T22:44:26.040578+00:00 app[web.1]: 	at com.mongodb.connection.AsynchronousSocketChannelStreamFactoryFactory.create(AsynchronousSocketChannelStreamFactoryFactory.java:28)
2017-05-05T22:44:26.040639+00:00 app[web.1]: 	at com.mongodb.async.client.MongoClients.getStreamFactory(MongoClients.java:136)
2017-05-05T22:44:26.040752+00:00 app[web.1]: 	at io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder.mongo(MongoClientImpl.java:709)
2017-05-05T22:44:26.040688+00:00 app[web.1]: 	at com.mongodb.async.client.MongoClients.create(MongoClients.java:61)
2017-05-05T22:44:26.040809+00:00 app[web.1]: 	at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:77)
2017-05-05T22:44:26.040877+00:00 app[web.1]: 	at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:66)
`

According to [official mongo-java-driver TLS/SSL docs](http://mongodb.github.io/mongo-java-driver/3.4/driver-async/tutorials/ssl/#tls-ssl), **streamType=netty** and/or **sslInvalidHostNameAllowed=true** parameters for ConnectionString, additionally to **ssl=**, are supported.

I can also confirm that `System.setProperty("org.mongodb.async.type", "netty");` workaround seems to be working but deprecated since 3.1 driver according to the previous doc.

So 👍  :)

**Comment by leolux** [comment]
How to configure vertx-mongo-client to add **streamType=netty** to the ConnectionString?

**Comment by zyclonite** [comment]
with the mongo driver (3.10.1) used in release 3.7, ssl works even without the netty stream type
