### ISSUE TITLE
BUG: java.lang.NoSuchMethodError: org.bson.types.ObjectId.toHexString()Ljava/lang/String; 

### ISSUE THREAD

**Issue by fedorchuck** [vert-x3/vertx-mongo-client#109]
```groovy
java.lang.NoSuchMethodError: org.bson.types.ObjectId.toHexString()Ljava/lang/String;
	at com.mongodb.connection.ClusterId.<init>(ClusterId.java:47)
	at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:105)
	at com.mongodb.async.client.MongoClients.createMongoClient(MongoClients.java:188)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:181)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:123)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:70)
	at io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder.mongo(MongoClientImpl.java:923)
	at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:115)
	at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:66)
	at com.github.fedorchuck.remote_logger.dal.MongoClientVerticle.start(MongoClientVerticle.java:39)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```
On the line:
```groovy
 MongoClient mongoClient = MongoClient.createShared(vertx, mongoconfig);
```

**Comment by fedorchuck** [comment]
and here https://github.com/vert-x3/vertx-examples/issues/209

**Comment by fedorchuck** [comment]
Sorry, it's my fault. If you have dependency `org.mongodb:mongo-java-driver:2.10.1`, you get this error.
