### ISSUE TITLE
java.lang.IllegalArgumentException: clusterListener can not be null

### ISSUE THREAD

**Issue by Houdini** [vert-x3/vertx-mongo-client#119]
config:
```json
  "mongodb": {
    "connection_string": "mongodb://localhost:27017",
    "db_name": "test"
  }
```
kotlin code:
```
val mongo_config = KodeinLoader.loadConfig().getJsonObject("mongodb")
val mongo = MongoClient.createShared(vertx, mongo_config)
```

stacktrace:
```
java.lang.IllegalArgumentException: clusterListener can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
	at com.mongodb.connection.ClusterSettings$Builder.addClusterListener(ClusterSettings.java:218)
	at com.mongodb.connection.DefaultClusterFactory.getClusterSettings(DefaultClusterFactory.java:156)
	at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:114)
	at com.mongodb.async.client.MongoClients.createMongoClient(MongoClients.java:188)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:181)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:123)
	at com.mongodb.async.client.MongoClients.create(MongoClients.java:70)
	at io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder.mongo(MongoClientImpl.java:926)
	at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:115)
	at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:66)
	at verticles.Main.start(Main.kt:29)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$10(DeploymentManager.java:481)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abhinavsri** [comment]
Same Issue when using vertx mongo client 3.5.0 .
I am also using mongodb driver 3.6.1

**Comment by johnoliver** [comment]
I just ran into this, I found it was due to having an old version of org.mongodb:mongo-java-driver, check all your dependency versions to make sure everything has upgraded to mongo 3.6 and you dont have something lying around.

**Comment by onupamit** [comment]
I had the same problem but when I upgraded org.mongodb:mongo-java-driver to 3.9.1 then problem had gone away.

**Comment by johnoliver** [comment]
Think I will close this, can be re-opened if upgrading mongo-java-driver does not work for someone
