### ISSUE TITLE
replace does not work for bulkWrite 

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-mongo-client#127]
The following operation produces no matches and no replace:
```
List<BulkOperation> bulkReplaces = new ArrayList();
JsonObject filter = new JsonObject().put("_id", "validAndExistingIdString");
BulkOperation testReplace = BulkOperation.createReplace(filter, someJsonObj, false);
bulkReplaces.add(testReplace );
mongo.bulkWrite("collectionName", bulkReplaces, ar -> {
   //ar.result().getMatchedCount() returns 0
});
```
Why does bulkWrite not replace the document although the "_id" provided in the filter is valid and exists in the collection?

I use `("useObjectId", true)` and `System.setProperty("org.mongodb.async.type", "netty");` and  the release version 3.4.2.

**Comment by leolux** [comment]
There is already test method for this: 
https://github.com/vert-x3/vertx-mongo-client/blob/db2be2203cc43adc81f9b004091074fb23858a52/vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java#L1577

But the method is never invoked, when looking into the repository: 
https://github.com/vert-x3/vertx-mongo-client/search?utf8=%E2%9C%93&q=testBulkOperation_replace&type=

What do you suggest?

**Comment by karianna** [comment]
@leolux I'm not sure what you mean there.  The test is:

```
  @Test
  public void testBulkOperation_replace() {
    String collection = randomCollection();
    insertDocs(mongoClient, collection, 1, onSuccess(v -> {
      JsonObject filter = new JsonObject().put("num", 123);
      JsonObject replace = new JsonObject().put("foo", "replaced");
      BulkOperation bulkReplace = BulkOperation.createReplace(filter, replace);
      mongoClient.bulkWrite(collection, Arrays.asList(bulkReplace), onSuccess(bulkResult -> {
        assertEquals(0, bulkResult.getInsertedCount());
        assertEquals(1, bulkResult.getModifiedCount());
        assertEquals(0, bulkResult.getDeletedCount());
        assertEquals(1, bulkResult.getMatchedCount());
        assertEquals(0, bulkResult.getUpserts().size());
        mongoClient.find(collection, new JsonObject(), onSuccess(docs -> {
          assertEquals(1, docs.size());
          JsonObject foundDoc = docs.get(0);
          assertEquals("replaced", foundDoc.getString("foo"));
          assertNull(foundDoc.getInteger("num"));
          testComplete();
        }));
      }));
    }));
    await();
  }
```

Which contains a bulk operation 'replace' via the bulkWrite with bulkOperation passed in...

**Comment by leolux** [comment]
Your are right. Junit-Tests are executed automatically by the test runner. But the method does not test the same scenario.

Therefore I have added another test method which filters for the "_id" instead of the "name" property:
```
  @Test
  public void testBulkOperation_replaceById() {
    String collection = randomCollection();
    mongoClient.createCollection(collection, onSuccess(res -> {
      JsonObject doc = new JsonObject();
      doc.put("foo","bar");
      doc.put("num",123);
      mongoClient.insert(collection, doc, onSuccess(id -> {
        JsonObject filter = new JsonObject().put("_id", id);
        JsonObject replace = new JsonObject().put("foo", "replaced");
        BulkOperation bulkReplace = BulkOperation.createReplace(filter, replace);
        mongoClient.bulkWrite(collection, Arrays.asList(bulkReplace), onSuccess(bulkResult -> {
          assertEquals(0, bulkResult.getInsertedCount());
          assertEquals(1, bulkResult.getModifiedCount());
          assertEquals(0, bulkResult.getDeletedCount());
          assertEquals(1, bulkResult.getMatchedCount());
          assertEquals(0, bulkResult.getUpserts().size());
          mongoClient.find(collection, new JsonObject(), onSuccess(docs -> {
            assertEquals(1, docs.size());
            JsonObject foundDoc = docs.get(0);
            assertEquals("replaced", foundDoc.getString("foo"));
            assertNull(foundDoc.getInteger("num"));
            testComplete();
          }));
        }));
      }));
    }));
    await();
  }
```

The test result fails:
```
Tests run: 92, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.479 sec <<< FAILURE! - in io.vertx.ext.mongo.MongoClientWithObjectIdTest
testBulkOperation_replaceById(io.vertx.ext.mongo.MongoClientWithObjectIdTest)  Time elapsed: 0.104 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.ext.mongo.MongoClientTestBase.lambda$null$203(MongoClientTestBase.java:1614)
	at io.vertx.test.core.AsyncTestBase.lambda$onSuccess$1(AsyncTestBase.java:632)
	at io.vertx.ext.mongo.impl.MongoClientImpl.lambda$null$15(MongoClientImpl.java:749)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```
Should I create a pull request?

**Comment by karianna** [comment]
@leolux Ah - yes please, much obliged :-)

**Comment by leolux** [comment]
https://github.com/vert-x3/vertx-mongo-client/pull/128
