### ISSUE TITLE
Unknown BsonType exception when trying to save java.time.Instant field

### ISSUE THREAD

**Issue by eciuca** [vert-x3/vertx-mongo-client#141]
```java.lang.IllegalStateException: Unknown BsonType for '1521726105.445000000'
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeValue(AbstractJsonCodec.java:83)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.lambda$writeDocument$1(AbstractJsonCodec.java:261)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.lambda$forEach$0(JsonObjectCodec.java:120)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:119)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:23)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeDocument(AbstractJsonCodec.java:258)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.encode(AbstractJsonCodec.java:28)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:381)
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:371)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:74)
	at com.mongodb.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:58)
	at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:128)
	at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:145)
	at com.mongodb.connection.InternalStreamConnection.sendAndReceiveAsync(InternalStreamConnection.java:321)
	at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceiveAsync(UsageTrackingInternalConnection.java:113)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceiveAsync(DefaultConnectionPool.java:452)
	at com.mongodb.connection.CommandProtocolImpl.executeAsync(CommandProtocolImpl.java:91)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:200)
	at com.mongodb.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:279)
	at com.mongodb.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:151)
	at com.mongodb.operation.MixedBulkWriteOperation.executeCommandAsync(MixedBulkWriteOperation.java:382)
	at com.mongodb.operation.MixedBulkWriteOperation.executeBatchesAsync(MixedBulkWriteOperation.java:314)
	at com.mongodb.operation.MixedBulkWriteOperation.access$900(MixedBulkWriteOperation.java:66)
	at com.mongodb.operation.MixedBulkWriteOperation$2$1.call(MixedBulkWriteOperation.java:233)
	at com.mongodb.operation.OperationHelper.validateWriteRequests(OperationHelper.java:175)
	at com.mongodb.operation.MixedBulkWriteOperation$2.call(MixedBulkWriteOperation.java:216)
	at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:525)
	at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:522)
	at com.mongodb.connection.DefaultServer$1.onResult(DefaultServer.java:99)
	at com.mongodb.connection.DefaultServer$1.onResult(DefaultServer.java:90)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.DefaultConnectionPool.openAsync(DefaultConnectionPool.java:189)
	at com.mongodb.connection.DefaultConnectionPool.getAsync(DefaultConnectionPool.java:146)
	at com.mongodb.connection.DefaultServer.getConnectionAsync(DefaultServer.java:90)
	at com.mongodb.binding.AsyncClusterBinding$AsyncClusterBindingConnectionSource.getConnection(AsyncClusterBinding.java:114)
	at com.mongodb.async.client.ClientSessionBinding$SessionBindingAsyncConnectionSource.getConnection(ClientSessionBinding.java:124)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:522)
	at com.mongodb.operation.OperationHelper.access$100(OperationHelper.java:61)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:542)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:530)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.ClientSessionBinding$1.onResult(ClientSessionBinding.java:57)
	at com.mongodb.async.client.ClientSessionBinding$1.onResult(ClientSessionBinding.java:51)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:88)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:82)
	at com.mongodb.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:421)
	at com.mongodb.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:285)
	at com.mongodb.connection.BaseCluster.selectServerAsync(BaseCluster.java:145)
	at com.mongodb.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:82)
	at com.mongodb.binding.AsyncClusterBinding.getWriteConnectionSource(AsyncClusterBinding.java:77)
	at com.mongodb.async.client.ClientSessionBinding.getWriteConnectionSource(ClientSessionBinding.java:51)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:481)
	at com.mongodb.operation.MixedBulkWriteOperation.executeAsync(MixedBulkWriteOperation.java:210)
	at com.mongodb.async.client.AsyncOperationExecutorImpl$2.onResult(AsyncOperationExecutorImpl.java:100)
	at com.mongodb.async.client.AsyncOperationExecutorImpl$2.onResult(AsyncOperationExecutorImpl.java:92)
	at com.mongodb.async.client.ClientSessionHelper.createClientSession(ClientSessionHelper.java:60)
	at com.mongodb.async.client.ClientSessionHelper.withClientSession(ClientSessionHelper.java:48)
	at com.mongodb.async.client.AsyncOperationExecutorImpl.execute(AsyncOperationExecutorImpl.java:92)
	at com.mongodb.async.client.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1114)
	at com.mongodb.async.client.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:522)
	at com.mongodb.async.client.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:501)
	at com.mongodb.async.client.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:496)
	at io.vertx.ext.mongo.impl.MongoClientImpl.insertWithOptions(MongoClientImpl.java:167)
	at io.vertx.ext.mongo.impl.MongoClientImpl.insert(MongoClientImpl.java:153)
	at com.webgenerals.tsapp.microservices.subscriptions.domain.SubscriptionRepositoryImpl.save(SubscriptionRepositoryImpl.java:60)
	at com.webgenerals.tsapp.microservices.subscriptions.impl.SubscriptionServiceImpl.saveSubscription(SubscriptionServiceImpl.java:46)
	at com.webgenerals.tsapp.microservices.subscriptions.rest.SubscriptionsResource.lambda$subscribe$1(SubscriptionsResource.java:32)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:219)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:120)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:231)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:211)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:74)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:417)
	at io.vertx.core.http.impl.Http1xServerConnection.handleLastHttpContent(Http1xServerConnection.java:462)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:457)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:437)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:728)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:636)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by StephenOTT** [comment]
Very annoying issue...

The workaround for this:

1. Set JsonIgnore on the get method for the Instant. 
1. Create a new method that returns a JsonObject. Set the JsonPropery annotation to have the same attribute name was the value of the method you ignored. 
1. Then do `return new JsonObject().put(JsonObjectCodec.DATE_FIELD, getMyInstant().toString());`

**Comment by GJean** [comment]
Hello, with vertx mongo client in version 4.1.3, I have the same error with Instant fields in Object :


`java.lang.IllegalStateException: Unknown BsonType for '1631390172.063593000'
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeValue(AbstractJsonCodec.java:86) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.lambda$writeDocument$1(AbstractJsonCodec.java:277) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.lambda$forEach$0(JsonObjectCodec.java:124) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:123) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:25) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeDocument(AbstractJsonCodec.java:274) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.encode(AbstractJsonCodec.java:29) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[bson-4.1.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[bson-4.1.0.jar:?]
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:200) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187) ~[mongodb-driver-core-4.1.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[bson-4.1.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[bson-4.1.0.jar:?]
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:162) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceiveAsync(InternalStreamConnection.java:393) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceiveAsync(UsageTrackingInternalConnection.java:145) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceiveAsync(DefaultConnectionPool.java:527) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.executeAsync(CommandProtocolImpl.java:77) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:273) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:218) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:135) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommandAsync(MixedBulkWriteOperation.java:440) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBatchesAsync(MixedBulkWriteOperation.java:348) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation.access$1000(MixedBulkWriteOperation.java:76) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation$2$1.call(MixedBulkWriteOperation.java:228) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.validateWriteRequests(OperationHelper.java:269) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation$2.call(MixedBulkWriteOperation.java:211) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper$9.onResult(OperationHelper.java:733) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper$9.onResult(OperationHelper.java:730) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:116) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:105) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool.openAsync(DefaultConnectionPool.java:204) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool.getAsync(DefaultConnectionPool.java:154) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer.getConnectionAsync(DefaultServer.java:105) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$AsyncClusterBindingConnectionSource.getConnection(AsyncClusterBinding.java:131) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionBinding$SessionBindingAsyncConnectionSource.getConnection(ClientSessionBinding.java:140) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withAsyncConnectionSource(OperationHelper.java:730) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.access$200(OperationHelper.java:68) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:750) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:738) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionBinding$WrappingCallback.onResult(ClientSessionBinding.java:208) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionBinding$WrappingCallback.onResult(ClientSessionBinding.java:196) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:105) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:99) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:432) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:299) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.BaseCluster.selectServerAsync(BaseCluster.java:155) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.connection.SingleServerCluster.selectServerAsync(SingleServerCluster.java:42) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:99) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding.getWriteConnectionSource(AsyncClusterBinding.java:89) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionBinding.getWriteConnectionSource(ClientSessionBinding.java:66) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withAsyncConnection(OperationHelper.java:669) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeAsync(MixedBulkWriteOperation.java:205) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl$2$1.onResult(OperationExecutorImpl.java:129) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl$2$1.onResult(OperationExecutorImpl.java:123) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl.getReadWriteBinding(OperationExecutorImpl.java:177) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl.access$200(OperationExecutorImpl.java:43) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl$2.onResult(OperationExecutorImpl.java:121) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl$2.onResult(OperationExecutorImpl.java:115) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionHelper.createClientSession(ClientSessionHelper.java:60) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.ClientSessionHelper.withClientSession(ClientSessionHelper.java:51) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.OperationExecutorImpl.execute(OperationExecutorImpl.java:115) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.AsyncMongoCollectionImpl.executeSingleWriteRequest(AsyncMongoCollectionImpl.java:1067) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.AsyncMongoCollectionImpl.executeInsertOne(AsyncMongoCollectionImpl.java:465) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.async.client.AsyncMongoCollectionImpl.insertOne(AsyncMongoCollectionImpl.java:447) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.reactivestreams.client.internal.MongoCollectionImpl.lambda$insertOne$5(MongoCollectionImpl.java:351) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.requestInitialData(SingleResultCallbackSubscription.java:39) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.tryRequestInitialData(AbstractSubscription.java:177) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at com.mongodb.reactivestreams.client.internal.AbstractSubscription.request(AbstractSubscription.java:100) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at io.vertx.ext.mongo.impl.CompletionSubscriber.onSubscribe(CompletionSubscriber.java:36) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.<init>(SingleResultCallbackSubscription.java:34) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at com.mongodb.reactivestreams.client.internal.Publishers.lambda$publish$1(Publishers.java:69) ~[mongodb-driver-reactivestreams-4.1.0.jar:?]
	at io.vertx.ext.mongo.impl.MongoClientImpl.saveWithOptions(MongoClientImpl.java:154) ~[vertx-mongo-client-4.1.3.jar:4.1.3]
	at io.vertx.ext.mongo.impl.MongoClientImpl.save(MongoClientImpl.java:134) ~[vertx-mongo-client-4.1.3.jar:4.1.3]`

**Comment by pmlopes** [comment]
This issue seems to be fixed in master. Adding `Instant.now()` as a value is correctly sent to the database.
