### ISSUE TITLE
java.lang.IllegalStateException when using future completer

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-mongo-client#143]
I cannot chain mongo operations with Futures because MongoClientImpl.java:758 somehow completes my future too early:

```
Future updateFuture = new Future();
executeUpdate("myCollection", updateFuture.completer());

 
private void executeUpdate(String collection, Handler<AsyncResult<Boolean>> completer) {
 //init query, update and options
 mongo.updateCollectionWithOptions(collection, query, update, options, res -> {
        if (res.succeeded()) {         
          completer.handle(Future.succeededFuture(true)); // <-- Here occurs the exception
        } else {          
          completer.handle(Future.failedFuture(res.cause()));
        }
      });
}
```
The exception looks like this:
```
 [io.vertx.core.impl.ContextImpl] - Unhandled exception java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:84)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at node.UpdateDocuments.lambda$executeUpdate$3(UpdateDocuments.java:10)
	at io.vertx.ext.mongo.impl.MongoClientImpl.lambda$null$11(MongoClientImpl.java:758)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

I use version 3.5.1

**Comment by tsegismont** [comment]
@leolux can you provide the client code snippet? I can't see anything wrong in what the MongoClient is doing here

**Comment by leolux** [comment]
The snippet comes from vertx-mongo-client-3.5.1-sources.jar and is linked by the stackstrace:
'''
  private <T, R> SingleResultCallback<T> convertCallback(Handler<AsyncResult<R>> resultHandler, 
Function<T, R> converter) {
    Context context = vertx.getOrCreateContext();
    return (result, error) -> {
      context.runOnContext(v -> {
        if (error != null) {
          resultHandler.handle(Future.failedFuture(error));
        } else {
          resultHandler.handle(Future.succeededFuture(converter.apply(result))); //<-- this is line 758 
        }
      });
    };
  }
'''
Note: The actual database operation completes successfully so it seems to be a minor bug.

**Comment by tsegismont** [comment]
@leolux I can see that. However I still fail to see how the Mongo Client is involved. In the snippets, the `updateFuture` is completed just once in the handler provided to the Mongo Client. I suspect it's completed elsewhere in your code. If I'm wrong, could you put together a small reproducer? Thanks

**Comment by leolux** [comment]
Alright, issue is within my code. It is as tsegismont said. My loop was completing the future to early.
