### ISSUE TITLE
Exception on RxJava2 and Mongo batch

### ISSUE THREAD

**Issue by max-grigoriev** [vert-x3/vertx-mongo-client#149]
Vertx version is 3.5.2.RC3
```
client.findBatchWithOptions("files", query, new FindOptions().setBatchSize(100)).toObservable()
        .map(doc -> {
            counter.incrementAndGet();
            if (counter.get() % 200 == 0) {
                log.debug("Received: {}", counter.get());
            }
            return doc;
        })
        .subscribe(doc -> {
                },
                err -> log.error("Exception during batching", err),
                () -> log.info("Complete batching"));
```

Give such error when no more records in the batch:

```
May 31, 2018 6:27:05 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalArgumentException: Stream is closed
	at io.vertx.ext.mongo.impl.MongoIterableStream.checkClosed(MongoIterableStream.java:52)
	at io.vertx.ext.mongo.impl.MongoIterableStream.exceptionHandler(MongoIterableStream.java:44)
	at io.vertx.ext.mongo.impl.MongoIterableStream.exceptionHandler(MongoIterableStream.java:20)
	at io.vertx.reactivex.core.impl.ObservableReadStream$Subscription.unset(ObservableReadStream.java:75)
	at io.vertx.reactivex.core.impl.ObservableReadStream$Subscription.cancel(ObservableReadStream.java:43)
	at io.vertx.reactivex.core.impl.ObservableReadStream$Subscription.lambda$set$0(ObservableReadStream.java:51)
	at io.vertx.ext.mongo.impl.MongoIterableStream.lambda$doRead$5(MongoIterableStream.java:141)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

But if I change `toObservable` to `toFlowable` then everything is OK

**Comment by karianna** [comment]
@johnoliver Bug or works as expected?

**Comment by tsegismont** [comment]
@karianna this is a bug in `MongoIterableStream` which is over-defensive. Please assign the issue to me, I'll take care of the fix.
