### ISSUE TITLE
MongoClient.createShared() needs to accept a result handler

### ISSUE THREAD

**Issue by lukehutch** [vert-x3/vertx-mongo-client#178]
`MongoClient.createShared()` does not take a `Handler` as a parameter, so it is not possible to react if MongoDB cannot be reached. (Ideally I would like my server to refuse to start if MongoDB is not running.)

**Comment by vietj** [comment]
@lukehutch I think in this case you need to have your own lookup method that will create the client and execute a _ping_ query to try reaching the server. The mongo client does not have such _ping_ method so I think it's the application that should make its own checks.

**Comment by lukehutch** [comment]
@vietj I tried this, hence #177. I don't see any way to issue a custom command with the result of `MongoClient.createShared()`, so I tried using the official MongoDB API, and there was a version conflict. How do I issue an arbitrary MongoDB command with Vertx' MongoClient?

**Comment by lukehutch** [comment]
@vietj I tried the following. Unfortunately `runCommand` never gets to run its command until the MongoDB server becomes available (which might be never), so there is no way to detect if the `MongoClient` creation was successful:

```
        mongoClient.runCommand("ping", new JsonObject().put("ping", "1"), result -> {
            if (result.succeeded()) {
                System.out.println("Mongo up");
            } else {
                System.out.println("Mongo down");
            }
        });
```

**Comment by lukehutch** [comment]
PS the exception thrown when MongoDB is down is the following:

```
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:268)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	... 1 more
```
