### ISSUE TITLE
Query failed with error code 2 and error message 'cannot set maxTimeMS on getMore command for a non-awaitData cursor' on server

### ISSUE THREAD

**Issue by yogs95** [vert-x3/vertx-mongo-client#222]
### Questions
While fetching results of aggregation pipeline in batches, I am getting below error when I am aggregating on mongo collection with vertx-mongo client, I tried with various options with AggregateOptions but didnt work.

The problem here it is not able to fetch subsequent batches after fetching the first batch, if I increase it to Integer.MAX it will work only for 16 mb of data in first batch and subsequent batches will fail again.

This issue is happening only with vertx-mongo, with normal async driver its working fine.

### Version
3.6.2

### Context
While doing aggregation operation for large data set where total records size is more than 16MB

### Steps to reproduce

1. JsonObject config = new JsonObject()
                .put("host", config().getString("host", ""))
                .put("port", Integer.parseInt(config().getString("port", "27017")))
                .put("username", config().getString("username", ""))
                .put("password", config().getString("password", ""))
                .put("db_name", config().getString("db_name", ""))
                //.put("authSource", config().getString("pricing_authSource", ""))
                .put(MongoConstants.USE_OBJECT_ID_KEY, true);

2. MongoClient mongoClient = MongoClient.createNonShared(this.vertx, config);
3. AggregateOptions options = new AggregateOptions()
                //.setMaxTime(20000)
                //.setMaxAwaitTime(20000)
                .setBatchSize(20)
                .setAllowDiskUse(true);

4.  return this.mongoClient.aggregateWithOptions(aggregationCollection, pipeline, options)
                .toFlowable()
                .map(res -> res.getString("_id"))
                .toList();

### Extra
JDK 1.8+
OS: Ubuntu

### Stack Trace
`com.mongodb.MongoQueryException: Query failed with error code 2 and error message 'cannot set maxTimeMS on getMore command for a non-awaitData cursor' on server localhost:27017
at com.mongodb.operation.QueryHelper.translateCommandException(QueryHelper.java:31)
    at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:294)
    at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:276)
    at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:205)
    at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    at com.mongodb.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:100)
    at com.mongodb.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:458)
    at com.mongodb.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:110)
    at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
    at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:383)
    at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:359)
    at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
    at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
    at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
    at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
    at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:233)
    at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:216)
    at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
    at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
    at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
    at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
    at com.mongodb.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:128)
    at com.mongodb.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:484)
    at com.mongodb.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:74)
    at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608)
    at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593)
    at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
    at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
    at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:233)
    at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:216)
    at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:439)
    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
    at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
    at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by yogs95** [comment]
I Have resolved this issue,
There was bug in AggregateOptions, setMaxAwaitTime has 1000L by default and if it id more than 0 then they are setting this option while executing aggregation, but aggregation returns non-awaitData cursor and you cant set the setMaxAwaitTime to non-awaitData cursor

So I have set the setMaxAwaitTime options to 0, typically my options looks like below

AggregateOptions options = new AggregateOptions()
                .setBatchSize(10000)
                .setMaxAwaitTime(0)
                .setAllowDiskUse(true);

**Comment by yogs95** [comment]
Hey @karianna Im just thinking 
its better to address this issue so that we can avoid the work around from the client side code.

**Comment by yogs95** [comment]
already an issue raised for similar concern 
https://github.com/vert-x3/vertx-mongo-client/pull/209
