### ISSUE TITLE
not compatible with org.mongodb:mongodb-driver-reactivestreams:5.0.0 (*) && org.mongodb:mongodb-driver-sync:5.0.0

### ISSUE THREAD

**Issue by marcelloceschia** [vert-x3/vertx-mongo-client#314]
### Questions

when trying to use version 4.5.5 together with org.mongodb:mongodb-driver-sync:5.0.0 we get the following error:

```
java.lang.NoClassDefFoundError: com/mongodb/connection/StreamFactoryFactory
	at io.vertx.ext.mongo.impl.config.StreamTypeParser$StreamType.<clinit>(StreamTypeParser.java:24)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.vertx.ext.mongo.impl.config.StreamTypeParser.streamFactory(StreamTypeParser.java:19)
	at io.vertx.ext.mongo.impl.config.MongoClientOptionsParser.<init>(MongoClientOptionsParser.java:60)
	at io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder.mongo(MongoClientImpl.java:1394)
	at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:100)
	at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:73)
```

### Version

io.vertx:vertx-mongo-client:4.5.5

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

If needed, I can create a simple project to demonstrate the issue

### Extra

* macOS with openjdk version "21.0.2" 2024-01-16

**Comment by tsegismont** [comment]
Can you share a sample pom? Thank you

**Comment by cazacugmihai** [comment]
I'm encountering the same problem with these dependencies:

```
io.vertx:vertx-mongo-client:4.5.8
org.mongodb:bson:5.1.0
org.mongodb:mongodb-driver-core:5.1.0`
org.mongodb:mongodb-driver-reactivestreams:5.1.0
```

Error:

```
java.lang.NoClassDefFoundError: com/mongodb/connection/StreamFactoryFactory
	at io.vertx.ext.mongo.impl.config.StreamTypeParser.streamFactory(StreamTypeParser.java:19) ~[vertx-mongo-client-4.5.8.jar:4.5.8]
	at io.vertx.ext.mongo.impl.config.MongoClientOptionsParser.<init>(MongoClientOptionsParser.java:60) ~[vertx-mongo-client-4.5.8.jar:4.5.8]
	at io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder.mongo(MongoClientImpl.java:1394) ~[vertx-mongo-client-4.5.8.jar:4.5.8]
	at io.vertx.ext.mongo.impl.MongoClientImpl.<init>(MongoClientImpl.java:100) ~[vertx-mongo-client-4.5.8.jar:4.5.8]
	at io.vertx.ext.mongo.MongoClient.createShared(MongoClient.java:62) ~[vertx-mongo-client-4.5.8.jar:4.5.8]
	at io.vertx.rxjava3.ext.mongo.MongoClient.createShared(MongoClient.java:110) ~[vertx-rx-java3-4.5.8.jar:4.5.8]
```
