### ISSUE TITLE
Exeption in MongoClient.update

### ISSUE THREAD

**Issue by remi128** [vert-x3/vertx-mongo-client#64]
When i am trying to update a document into Mongo by using the method MongoClient.update( ... ) i am getting an Exception like:

 java.lang.IllegalArgumentException: Invalid BSON field name intValue
	at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:494)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.lambda$writeDocument$1(AbstractJsonCodec.java:254)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec$$Lambda$35/951031848.accept(Unknown Source)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.lambda$forEach$3(JsonObjectCodec.java:97)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec$$Lambda$36/1408482749.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
        ...

on the first field inside the document. Renaming doesn't matter.
If i'm switching to MongoClient.save( ... ) everything is working fine

**Comment by pmlopes** [comment]
@remi128 can you share the line of code you're executing? it might help to troubleshoot the issue

**Comment by remi128** [comment]
@pmlopes I'll prepare something and come back with it next week

**Comment by diabolicallabs** [comment]
I'm guessing that you didn't "$set" the field to update in your document. On an update you have to do something like this:

JsonObject updateDoc = new JsonObject().put("$set", new JsonObject().put("intValue", 13))

mongoclient.update(query, updateDoc, ....

A save doesn't require this.

**Comment by remi128** [comment]
yes, that was it
